"""add avatar and banner to user

Revision ID: 4478a1b03f05
Revises: 6801400661c2
Create Date: 2026-05-06 11:32:08.269412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4478a1b03f05'
down_revision = '6801400661c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('banner_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('banner_url')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
