"""add itinerary submit fields

Revision ID: 6801400661c2
Revises: 4acbfbe65bbb
Create Date: 2026-05-02 21:11:12.361989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6801400661c2'
down_revision = '4acbfbe65bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_types', sa.JSON(), nullable=False))

    with op.batch_alter_table('itinerary_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(length=100), nullable=True))

    with op.batch_alter_table('itinerary_day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('transport', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('transport_other_text', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('restaurants', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('restaurant_specific', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('accommodations', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('accommodation_specific', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_day', schema=None) as batch_op:
        batch_op.drop_column('accommodation_specific')
        batch_op.drop_column('accommodations')
        batch_op.drop_column('restaurant_specific')
        batch_op.drop_column('restaurants')
        batch_op.drop_column('transport_other_text')
        batch_op.drop_column('transport')
        batch_op.drop_column('city')
        batch_op.drop_column('state')

    with op.batch_alter_table('itinerary_activity', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('place')

    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_column('trip_types')

    # ### end Alembic commands ###
